functionsDirectory = "/Users/adda247/YT Dashboard/YoutubeVideoDetails/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/adda247/YT Dashboard/YoutubeVideoDetails/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/adda247/YT Dashboard/YoutubeVideoDetails/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]